name: Cloud Custodian Policies

on:
  push:
    branches:
      - cloud-custodian
  pull_request:
    branches:
      - cloud-custodian

jobs:
  cloud-custodian:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: print hello
      run: echo "hello"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install pip
      run: python -m ensurepip

    - name: Install custodian
      run: pip install custodian

    - name: Install c7n
      run: pip install c7n

    - name: Set up jq
      run: sudo apt-get install jq

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 

    - name: Checkout specific repository and branch
      uses: actions/checkout@v4
      with:
        repository: shivanbgtsi/devopsnxt-iac
        ref: cloud-custodian    

    - name: Run custodian policies
      run: |
        cd ${{ github.workspace }}/cc-policies
        custodian run -s output --cache-period 0 --cache output/cache --region ap-south-1  policy.yaml 
        cd output/test-s3-bucket-public-access
        cat resources.json
