name: Shellspec Test for AWS SSM Parameters

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  shellspec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: print hello
      run: echo "hello"
