name: DevOps-Nxt github action infra

on:
  push:
    branches:
      - feature-github-actions
  pull_request:
    branches:
      - feature-github-actions

jobs:
  shellspec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: check Terraform version
      run: terraform -v
    
